service: hello

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi: GET /hello

plugins:
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false