service: hexagonal-architecture-example

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'develop'}
  region: ${opt:region, 'us-east-1'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
          Resource: !GetAtt StockTable.Arn

functions:
  stockValues:
    handler: src/infrastructure/lambdas/stock.handler
    events:
      - http:
          path: /stock/{stockId}
          method: GET
          request:
            parameters:
              paths:
                stockId: true
    environment:
      API_KEY: ${env:API_KEY}
      DB_TABLE: !Ref StockTable

plugins:
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false

resources:
  Resources:
    StockTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}
        AttributeDefinitions:
          - AttributeName: STOCK_ID
            AttributeType: S
        KeySchema:
          - AttributeName: STOCK_ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST